// 会員データのインポート実行用のファイル
const dotenv = require('dotenv');
const { initializeApp } = require('firebase/app');
const { getFirestore, collection, addDoc, Timestamp } = require('firebase/firestore');

// 環境変数をロード
dotenv.config({ path: '.env.local' });

// Firebase設定
const firebaseConfig = {
  apiKey: process.env.NEXT_PUBLIC_FIREBASE_API_KEY,
  authDomain: process.env.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN,
  projectId: process.env.NEXT_PUBLIC_FIREBASE_PROJECT_ID,
  storageBucket: process.env.NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET,
  messagingSenderId: process.env.NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID,
  appId: process.env.NEXT_PUBLIC_FIREBASE_APP_ID,
};

// Firebaseを初期化
const app = initializeApp(firebaseConfig);
const db = getFirestore(app);

// 会員データ
const members = [
  {
    name: "小松 沙織",
    furigana: "こまつ さおり",
    types: ["ベビーマッサージマスター", "ベビーヨガマスター"],
    type: "ベビーマッサージマスター",
    number: "19-00002",
    phone: "",
    prefecture: "",
    address: "",
  },
  {
    name: "桐谷 舞",
    furigana: "きりたに まい",
    types: ["ベビーマッサージマスター", "ベビーヨガマスター"],
    type: "ベビーマッサージマスター",
    phone: "090-9874-4033",
    prefecture: "大阪府",
    address: "大阪市淀川区新高4-3-11",
    number: "19-00003",
  },
  {
    name: "𠮷田 絢視",
    furigana: "よしだ あやみ",
    types: ["ベビーマッサージインストラクター", "ベビーヨガインストラクター"],
    type: "ベビーマッサージインストラクター",
    phone: "070-2422-8583",
    prefecture: "大阪府",
    address: "大阪市鶴見区放出東2-7-3 ブランシュネージュ101",
    number: "19-00004",
  },
  {
    name: "灘友 千紘",
    furigana: "なだとも ちひろ",
    types: ["ベビーヨガインストラクター"],
    type: "ベビーヨガインストラクター",
    phone: "090-4122-7293",
    prefecture: "京都府",
    address: "京都府向日市寺戸町寺田５０－１－４２１",
    number: "20-00005",
  },
  {
    name: "朝田 海瑠",
    furigana: "あさだ みる",
    types: ["ベビーマッサージ"],
    type: "ベビーマッサージ",
    phone: "",
    prefecture: "",
    address: "",
    number: "19-00005",
  },
  {
    name: "三原 亜里沙",
    furigana: "みはら ありさ",
    types: ["ベビーマッサージインストラクター", "ベビーヨガインストラクター"],
    type: "ベビーマッサージインストラクター",
    phone: "",
    prefecture: "",
    address: "",
    number: "19-00006",
  },
  {
    name: "中野 遥乃",
    furigana: "",
    types: ["ベビーマッサージインストラクター", "ベビーヨガインストラクター"],
    type: "ベビーマッサージインストラクター",
    phone: "",
    prefecture: "",
    address: "",
    number: "",
  },
  {
    name: "和田 久子",
    furigana: "わだ ひさこ",
    types: ["ベビーヨガインストラクター"],
    type: "ベビーヨガインストラクター",
    phone: "",
    prefecture: "",
    address: "",
    number: "20-00007",
  },
  {
    name: "松尾 ちか",
    furigana: "まつお ちか",
    types: ["ベビーマッサージインストラクター"],
    type: "ベビーマッサージインストラクター",
    phone: "",
    prefecture: "",
    address: "",
    number: "",
  },
  {
    name: "塚本 美穂",
    furigana: "",
    types: ["ベビーマッサージ", "ベビーヨガ"],
    type: "ベビーマッサージ",
    phone: "",
    prefecture: "",
    address: "",
    number: "",
  },
  {
    name: "熊谷 裕美",
    furigana: "くまがい ゆみ",
    types: ["知育あそび"],
    type: "知育あそび",
    phone: "",
    prefecture: "",
    address: "",
    number: "",
  },
  {
    name: "中川 志歩",
    furigana: "なかがわ しほ",
    types: ["ベビーマッサージインストラクター", "ベビーヨガインストラクター", "マスター"],
    type: "ベビーマッサージインストラクター",
    phone: "",
    prefecture: "",
    address: "",
    number: "",
  },
  {
    name: "清田 優香",
    furigana: "きよた ゆか",
    types: ["ベビーマッサージ"],
    type: "ベビーマッサージ",
    phone: "",
    prefecture: "",
    address: "",
    number: "",
  },
  {
    name: "島田 千尋",
    furigana: "しまだ ちひろ",
    types: ["ベビーマッサージ", "ベビーヨガ"],
    type: "ベビーマッサージ",
    phone: "",
    prefecture: "",
    address: "",
    number: "",
  },
  {
    name: "尾崎 実祈",
    furigana: "おざき みるき",
    types: ["ベビーマッサージインストラクター", "ベビーヨガインストラクター"],
    type: "ベビーマッサージインストラクター",
    phone: "",
    prefecture: "",
    address: "",
    number: "",
  },
  {
    name: "小林 光代",
    furigana: "こばやし みつよ",
    types: ["ベビーマッサージ", "ベビーヨガ"],
    type: "ベビーマッサージ",
    phone: "",
    prefecture: "",
    address: "",
    number: "",
  },
  {
    name: "吉田 小百合",
    furigana: "よしだ さゆり",
    types: ["ベビーマッサージ", "ベビーヨガ"],
    type: "ベビーマッサージ",
    phone: "080-3888-7092",
    prefecture: "広島県",
    address: "広島県福山市新涯町３－２６ー３０カーサ・セレーノB101",
    number: "2207",
  },
  {
    name: "山下 夕貴",
    furigana: "やました ゆうき",
    types: ["ベビーマッサージ"],
    type: "ベビーマッサージ",
    phone: "080-4322-1212",
    prefecture: "大阪府",
    address: "大阪府柏原市国分西２－６－２２－４０５",
    number: "2208",
  },
  {
    name: "山田 未紗",
    furigana: "やまだ みさ",
    types: ["ベビーマッサージインストラクター", "ベビーヨガインストラクター"],
    type: "ベビーマッサージインストラクター",
    phone: "080-3138-6780",
    prefecture: "大阪府",
    address: "大阪市住之江区北島２－３－１４",
    number: "2302",
  },
  {
    name: "岡本 幸歩",
    furigana: "おかもと ゆきほ",
    types: ["ベビーマッサージインストラクター", "ベビーヨガインストラクター"],
    type: "ベビーマッサージインストラクター",
    phone: "080-3867-3906",
    prefecture: "兵庫県",
    address: "兵庫県伊丹市高台３－７０サニーハイツ高台C棟２０２",
    number: "2303",
  },
  {
    name: "冷水 紗八佳",
    furigana: "ひやみず さやか",
    types: ["ベビーマッサージインストラクター", "ベビーヨガインストラクター"],
    type: "ベビーマッサージインストラクター",
    phone: "080-3811-3010",
    prefecture: "大阪府",
    address: "大阪市港区波除１－１－３７－１３０７",
    number: "2204",
  },
  {
    name: "樺澤 雅子",
    furigana: "かばさわ まさこ",
    types: ["ベビーマッサージインストラクター", "ベビーヨガインストラクター"],
    type: "ベビーマッサージインストラクター",
    phone: "090-7235-1730",
    prefecture: "千葉県",
    address: "千葉県印西市原3-2-1020",
    number: "2209",
  },
  {
    name: "原田 典子",
    furigana: "はらだ のりこ",
    types: ["ベビーマッサージ", "ベビーヨガ"],
    type: "ベビーマッサージ",
    phone: "090-9588-8360",
    prefecture: "兵庫県",
    address: "兵庫県淡路市久留麻１４３－４",
    number: "2302",
  },
  {
    name: "徳島 佳央里",
    furigana: "とくしま かおり",
    types: ["ベビーマッサージインストラクター", "ベビーヨガインストラクター"],
    type: "ベビーマッサージインストラクター",
    phone: "090-4906-1786",
    prefecture: "大阪府",
    address: "大阪市生野区巽西４－５－１１",
    number: "2303",
  },
  {
    name: "山城 里佳",
    furigana: "やましろ りか",
    types: ["ベビーマッサージ"],
    type: "ベビーマッサージ",
    phone: "090-4745-5781",
    prefecture: "大阪府",
    address: "大阪市東淀川区菅原７－４－３",
    number: "2303",
  },
  {
    name: "佐藤 秀美",
    furigana: "さとう ひでみ",
    types: ["ベビーヨガインストラクター"],
    type: "ベビーヨガインストラクター",
    phone: "090-1621-0484",
    prefecture: "大阪府",
    address: "大阪市西区南堀江２－３－７",
    number: "2304",
  },
  {
    name: "近藤 小夜",
    furigana: "こんどう せれな",
    types: ["ベビーマッサージ", "ベビーヨガ"],
    type: "ベビーマッサージ",
    phone: "090-3826-1129",
    prefecture: "大阪府",
    address: "大阪市北区本庄東３－８－３ー６０５",
    number: "2304",
  },
  {
    name: "田中 和枝",
    furigana: "たなか かずえ",
    types: ["ベビーマッサージ", "ベビーヨガ"],
    type: "ベビーマッサージ",
    phone: "080-3139-5525",
    prefecture: "大阪府",
    address: "大阪市城東区東中浜６－１７－２５－３０６",
    number: "2301",
  },
  {
    name: "中原 愛理",
    furigana: "なかはら あいり",
    types: ["ベビーマッサージインストラクター", "ベビーヨガインストラクター"],
    type: "ベビーマッサージインストラクター",
    phone: "",
    prefecture: "大阪府",
    address: "大阪市西区川口３－９－２ー６１０",
    number: "2204",
  },
  {
    name: "河北 みゆき",
    furigana: "かわきた みゆき",
    types: ["ベビーマッサージ", "ベビーヨガ"],
    type: "ベビーマッサージ",
    phone: "090-3728-9689",
    prefecture: "鹿児島県",
    address: "鹿児島県鹿児島市宇宿２－２４－８ディアコート宇宿２０２",
    number: "2304",
  },
  {
    name: "仲野 美由紀",
    furigana: "なかの みゆき",
    types: ["ベビーマッサージインストラクター", "ベビーヨガインストラクター"],
    type: "ベビーマッサージインストラクター",
    phone: "080-4365-3960",
    prefecture: "北海道",
    address: "北海道千歳市あずさ５－１６－１０",
    number: "2206",
  },
  {
    name: "大西 理恵",
    furigana: "おおにし りえ",
    types: ["ベビーマッサージインストラクター", "ベビーヨガインストラクター"],
    type: "ベビーマッサージインストラクター",
    phone: "090-1227-1641",
    prefecture: "大阪府",
    address: "大阪市鶴見区今津北５－７－８－１２０７",
    number: "2204",
  },
  {
    name: "南 紀子",
    furigana: "みなみ のりこ",
    types: ["ベビーマッサージインストラクター", "ベビーヨガインストラクター"],
    type: "ベビーマッサージインストラクター",
    phone: "090-104-8962",
    prefecture: "大阪府",
    address: "大阪市東淀川区豊里6-14-4-201",
    number: "2204",
  },
  {
    name: "大内 美津江",
    furigana: "おおうち みつえ",
    types: ["ベビーマッサージインストラクター", "ベビーヨガインストラクター"],
    type: "ベビーマッサージインストラクター",
    phone: "",
    prefecture: "兵庫県",
    address: "",
    number: "2203",
  },
  {
    name: "辻本 彩音",
    furigana: "つじもと あやね",
    types: ["ベビーマッサージインストラクター", "ベビーヨガインストラクター"],
    type: "ベビーマッサージインストラクター",
    phone: "090-1713-4640",
    prefecture: "大阪府",
    address: "大阪府寝屋川市黒原新町9-13 ザ・ヴァンデュールシティ722",
    number: "2207",
  },
  {
    name: "上田 咲子",
    furigana: "うえだ さきこ",
    types: ["ベビーマッサージ"],
    type: "ベビーマッサージ",
    phone: "090-5241-1709",
    prefecture: "大阪府",
    address: "大阪府枚方市香里園町12-55",
    number: "2212",
  },
  {
    name: "澤井 咲弥花",
    furigana: "さわい さやか",
    types: ["ベビーマッサージ", "ベビーヨガ"],
    type: "ベビーマッサージ",
    phone: "",
    prefecture: "",
    address: "",
    number: "2212",
  },
  {
    name: "伊藤 侑依",
    furigana: "いとう ゆい",
    types: ["ベビーマッサージ"],
    type: "ベビーマッサージ",
    phone: "090-3448-0998",
    prefecture: "愛知県",
    address: "愛知県名古屋市緑区鳴海町字山腰30-4",
    number: "2212",
  },
  {
    name: "遠藤 友実",
    furigana: "えんどう ともみ",
    types: ["ベビーマッサージ", "ベビーヨガ"],
    type: "ベビーマッサージ",
    phone: "080-1423-0621",
    prefecture: "兵庫県",
    address: "兵庫県神戸市東灘区御影山手3-1-1-A103",
    number: "2211",
  },
  {
    name: "宿谷 愛美",
    furigana: "しゅくや まなみ",
    types: ["ベビーマッサージ", "ベビーヨガ"],
    type: "ベビーマッサージ",
    phone: "090-6203-3818",
    prefecture: "奈良県",
    address: "奈良県香芝市真美ヶ丘2-1-30 スカイビレA202",
    number: "2208",
  },
  {
    name: "藤原 柚香",
    furigana: "ふじわら ゆか",
    types: ["ベビーマッサージ", "ベビーヨガ"],
    type: "ベビーマッサージ",
    phone: "090-9982-2066",
    prefecture: "大阪府",
    address: "大阪狭山市狭山3-2556-4 エフイー大阪狭山201",
    number: "2210",
  },
  {
    name: "森岡 紗枝",
    furigana: "もりおか さえ",
    types: ["ベビーマッサージ", "ベビーヨガ"],
    type: "ベビーマッサージ",
    phone: "090-1893-2522",
    prefecture: "大阪府",
    address: "大阪市西区靭本町1-19-16-305",
    number: "2208",
  },
  {
    name: "冨岡 あすか",
    furigana: "とみおか あすか",
    types: ["ベビーマッサージ", "ベビーヨガ"],
    type: "ベビーマッサージ",
    phone: "080-6186-0782",
    prefecture: "大阪府",
    address: "大阪市城東区新喜多1-2-7-3009",
    number: "2208",
  },
  {
    name: "中村 梓沙",
    furigana: "なかむら あずさ",
    types: ["ベビーマッサージ", "ベビーヨガ"],
    type: "ベビーマッサージ",
    phone: "080-3847-9370",
    prefecture: "大阪府",
    address: "大阪市東住吉区湯里4-14-3",
    number: "2209",
  },
  {
    name: "内田 奈穂子",
    furigana: "うちだ なほこ",
    types: ["ベビーマッサージ", "ベビーヨガ"],
    type: "ベビーマッサージ",
    phone: "",
    prefecture: "大阪府",
    address: "",
    number: "2203",
  },
  {
    name: "上田 由樹",
    furigana: "うえだ ゆき",
    types: ["ベビーマッサージ", "ベビーヨガ"],
    type: "ベビーマッサージ",
    phone: "",
    prefecture: "大阪府",
    address: "",
    number: "2204",
  },
  {
    name: "牧野 唯",
    furigana: "まきの ゆい",
    types: ["ベビーマッサージ", "ベビーヨガ"],
    type: "ベビーマッサージ",
    phone: "",
    prefecture: "大阪府",
    address: "",
    number: "2204",
  },
  {
    name: "橋本 萌",
    furigana: "はしもと もえ",
    types: ["ベビーマッサージ"],
    type: "ベビーマッサージ",
    phone: "",
    prefecture: "大阪府",
    address: "",
    number: "2204",
  },
  {
    name: "松本 美紀",
    furigana: "まつもと みき",
    types: ["ベビーマッサージ", "ベビーヨガ"],
    type: "ベビーマッサージ",
    phone: "",
    prefecture: "大阪府",
    address: "",
    number: "2203",
  },
  {
    name: "井本 景子",
    furigana: "いもと けいこ",
    types: ["ベビーマッサージ", "ベビーヨガ"],
    type: "ベビーマッサージ",
    phone: "090-4274-1471",
    prefecture: "大阪府",
    address: "大阪市淀川区三国本町3-18-17",
    number: "2206",
  },
  {
    name: "髙橋 美紀",
    furigana: "たかはし みき",
    types: ["ベビーマッサージ", "ベビーヨガ"],
    type: "ベビーマッサージ",
    phone: "",
    prefecture: "大阪府",
    address: "",
    number: "2203",
  },
  {
    name: "河田 理恵",
    furigana: "かわた りえ",
    types: ["ベビーマッサージインストラクター", "ベビーヨガインストラクター"],
    type: "ベビーマッサージインストラクター",
    phone: "",
    prefecture: "",
    address: "",
    number: "2301",
  },
  {
    name: "山南 美沙子",
    furigana: "やまなみ みさこ",
    types: ["ベビーマッサージインストラクター", "ベビーヨガインストラクター"],
    type: "ベビーマッサージインストラクター",
    phone: "",
    prefecture: "",
    address: "",
    number: "2204",
  },
  {
    name: "飯田 明日香",
    furigana: "いいだ あすか",
    types: ["ベビーマッサージインストラクター", "ベビーヨガインストラクター"],
    type: "ベビーマッサージインストラクター",
    phone: "",
    prefecture: "",
    address: "",
    number: "2203",
  },
  {
    name: "磯山 かおり",
    furigana: "いそやま かおり",
    types: ["開業サポート講座"],
    type: "開業サポート講座",
    phone: "",
    prefecture: "",
    address: "",
    number: "2304",
  }
];

// Firestoreに追加
async function addMembers() {
  try {
    console.log('会員データの追加を開始します...');
    const membersRef = collection(db, 'members');
    
    for (const member of members) {
      const now = Timestamp.now();
      const newMember = {
        ...member,
        createdAt: now,
        updatedAt: now,
      };
      
      const docRef = await addDoc(membersRef, newMember);
      console.log(`会員を追加しました: ${member.name}, ID: ${docRef.id}`);
    }
    
    console.log('すべての会員データの追加が完了しました！');
  } catch (error) {
    console.error('エラーが発生しました:', error);
  }
}

// 会員データを追加
addMembers(); 